version: "3.8"

services:
  registro-kiko:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: registro-kiko
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env:ro
    environment:
      - NODE_ENV=production
    networks:
      - proxy

networks:
  proxy:
    external: true
